title: Isabella # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Italian/Brazilian
  <br><br>
  Mainly interested in health, family and gender economics. Also interested in nutrition, food security and rural development.
  <br><br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
